### ISSUE TITLE
Sorry for disturbing you here..

### ISSUE THREAD

**Issue by Zorrototo** [andregomesdepaiva/Invoice-Manager#1]
... but I didn't find another way to contact you. I see you in the front page of https://github.com/OpenGamePanel in the "People" box on the right side, pretty much since I joined GitHub. So far I couldn't find who you are.. so I'm asking you here :D 

I'm Omano from OGP forum. Are you from OGP forum too or are you just a random person who added OGP in his 'organization' in profile? This is bothering me for so long that I need to know who you are :D 

Cheers.

**Comment by andregomesdepaiva** [comment]
Hello


My name is Andre, and i once was a small contributor to the OGP project. I also started the porting from sourceforge to github, so that's why you see me on the People table (the other people has set their profiles as private!)


Thanks,

Andre

________________________________
De: ®omano <notifications@github.com>
Enviado: terça-feira, 12 de setembro de 2017 22:35:01
Para: andregomesdepaiva/Invoice-Manager
Cc: Subscribed
Assunto: [andregomesdepaiva/Invoice-Manager] Sorry for disturbing you here.. (#1)


... but I didn't find another way to contact you. I see you in the front page of https://github.com/OpenGamePanel in the "People" box on the right side, pretty much since I joined GitHub. So far I couldn't find who you are.. so I'm asking you here :D

I'm Omano from OGP forum. Are you from OGP forum too or are you just a random person who added OGP in his 'organization' in profile? This is bothering me for so long that I need to know who you are 🗡

Cheers.

**Comment by andregomesdepaiva** [comment]
Can you contact me at agomesp@outlook.com?

**Comment by Zorrototo** [comment]
Can delete the whole issue to hide mail maybe ;)
